# Generated by Django 5.1.1 on 2024-09-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Status',
            new_name='status',
        ),
    ]
